image: gradle:4.7-jdk8-alpine

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

Build:
  stage: build
  script:
    - gradle clean build --refresh-dependencies

Test:
  stage: test
  coverage:'/Total.*?([0-9]{1,3})%/'
  script:
    - gradle -q check jacocoTestReport
    - gradle -q jacocoTestCoverageVerification
    - cat build/reports/jacoco/test/html/index.html

DeployProduction:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  when: manual
  environment:
    name: production
    url: $HEROKU_APP_HOST
